/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstadisticasVariablesDiscretasAgrupadasRouteImport } from './routes/estadisticas/variables-discretas-agrupadas'
import { Route as EstadisticasVariablesDiscretasRouteImport } from './routes/estadisticas/variables-discretas'
import { Route as EstadisticasVariablesContinuasRouteImport } from './routes/estadisticas/variables-continuas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasVariablesDiscretasAgrupadasRoute =
  EstadisticasVariablesDiscretasAgrupadasRouteImport.update({
    id: '/estadisticas/variables-discretas-agrupadas',
    path: '/estadisticas/variables-discretas-agrupadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstadisticasVariablesDiscretasRoute =
  EstadisticasVariablesDiscretasRouteImport.update({
    id: '/estadisticas/variables-discretas',
    path: '/estadisticas/variables-discretas',
    getParentRoute: () => rootRouteImport,
  } as any)
const EstadisticasVariablesContinuasRoute =
  EstadisticasVariablesContinuasRouteImport.update({
    id: '/estadisticas/variables-continuas',
    path: '/estadisticas/variables-continuas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estadisticas/variables-continuas': typeof EstadisticasVariablesContinuasRoute
  '/estadisticas/variables-discretas': typeof EstadisticasVariablesDiscretasRoute
  '/estadisticas/variables-discretas-agrupadas': typeof EstadisticasVariablesDiscretasAgrupadasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estadisticas/variables-continuas': typeof EstadisticasVariablesContinuasRoute
  '/estadisticas/variables-discretas': typeof EstadisticasVariablesDiscretasRoute
  '/estadisticas/variables-discretas-agrupadas': typeof EstadisticasVariablesDiscretasAgrupadasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estadisticas/variables-continuas': typeof EstadisticasVariablesContinuasRoute
  '/estadisticas/variables-discretas': typeof EstadisticasVariablesDiscretasRoute
  '/estadisticas/variables-discretas-agrupadas': typeof EstadisticasVariablesDiscretasAgrupadasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estadisticas/variables-continuas'
    | '/estadisticas/variables-discretas'
    | '/estadisticas/variables-discretas-agrupadas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estadisticas/variables-continuas'
    | '/estadisticas/variables-discretas'
    | '/estadisticas/variables-discretas-agrupadas'
  id:
    | '__root__'
    | '/'
    | '/estadisticas/variables-continuas'
    | '/estadisticas/variables-discretas'
    | '/estadisticas/variables-discretas-agrupadas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstadisticasVariablesContinuasRoute: typeof EstadisticasVariablesContinuasRoute
  EstadisticasVariablesDiscretasRoute: typeof EstadisticasVariablesDiscretasRoute
  EstadisticasVariablesDiscretasAgrupadasRoute: typeof EstadisticasVariablesDiscretasAgrupadasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/variables-discretas-agrupadas': {
      id: '/estadisticas/variables-discretas-agrupadas'
      path: '/estadisticas/variables-discretas-agrupadas'
      fullPath: '/estadisticas/variables-discretas-agrupadas'
      preLoaderRoute: typeof EstadisticasVariablesDiscretasAgrupadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/variables-discretas': {
      id: '/estadisticas/variables-discretas'
      path: '/estadisticas/variables-discretas'
      fullPath: '/estadisticas/variables-discretas'
      preLoaderRoute: typeof EstadisticasVariablesDiscretasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas/variables-continuas': {
      id: '/estadisticas/variables-continuas'
      path: '/estadisticas/variables-continuas'
      fullPath: '/estadisticas/variables-continuas'
      preLoaderRoute: typeof EstadisticasVariablesContinuasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstadisticasVariablesContinuasRoute: EstadisticasVariablesContinuasRoute,
  EstadisticasVariablesDiscretasRoute: EstadisticasVariablesDiscretasRoute,
  EstadisticasVariablesDiscretasAgrupadasRoute:
    EstadisticasVariablesDiscretasAgrupadasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
